name: android-platform-tools
adopt-info: tools
grade: stable
confinement: strict
base: core24
compression: lzo
license: Apache-2.0
summary: Android development tools
description: |
  Tools commonly used for Android development.
  Currently the following tools are supported:

  - adb
  - fastboot
  - mke2fs.android & make-f2fs (required by fastboot)
  - simg2img, img2simg, append2simg
  - lpdump, lpmake, lpadd, lpflash, lpunpack
  - mkbootimg, unpack_bootimg, repack_bootimg, avbtool

  In order to enable the full featureset you will have to
  grant permissions to this Snap:

  ```
  sudo snap connect android-platform-tools:adb-support
  sudo snap connect android-platform-tools:block-devices
  sudo snap connect android-platform-tools:raw-usb
  sudo snap connect android-platform-tools:removable-media
  sudo snap connect android-platform-tools:network
  sudo snap connect android-platform-tools:network-bind
  sudo snap connect android-platform-tools:block-devices
  ```

  Creating system-wide aliases is also possible:

  ```
  sudo snap alias android-platform-tools.adb adb
  sudo snap alias android-platform-tools.fastboot fastboot
  ```

platforms:
  arm64:
    build-on: [arm64]
  amd64:
    build-on: [amd64]
  armhf:
    build-on: [armhf]
  ppc64el:
    build-on: [ppc64el]
  riscv64:
    build-on: [riscv64]
  #s390x:
  #  build-on: [s390x]

apps:
  adb:
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
    command: usr/bin/adb
    completer: usr/share/android-tools/completions/adb
    plugs: [ adb-support, network, network-bind, raw-usb, home, removable-media ]
  fastboot:
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
    command: usr/bin/fastboot
    completer: usr/share/android-tools/completions/fastboot
    plugs: [ raw-usb, home, removable-media ]
  mke2fs-android:
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
    command: usr/bin/mke2fs.android
    plugs: [ home, removable-media ]
  make-f2fs:
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
    command: usr/bin/make_f2fs
    plugs: [ home, removable-media ]
  simg2img:
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
    command: usr/bin/simg2img
    plugs: [ home, removable-media ]
  img2simg:
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
    command: usr/bin/img2simg
    plugs: [ home, removable-media ]
  append2simg:
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
    command: usr/bin/append2simg
    plugs: [ home, removable-media ]
  lpdump:
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
    command: usr/bin/lpdump
    plugs: [ block-devices, home, removable-media ]
  lpmake:
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
    command: usr/bin/lpmake
    plugs: [ home, removable-media ]
  lpadd:
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
    command: usr/bin/lpadd
    plugs: [ home, removable-media ]
  lpflash:
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
    command: usr/bin/lpflash
    plugs: [ block-devices, home, removable-media ]
  lpunpack:
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
    command: usr/bin/lpunpack
    plugs: [ home, removable-media ]
  mkbootimg:
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
    command: usr/bin/python3 $SNAP/usr/bin/mkbootimg
    plugs: [ home, removable-media ]
  unpack-bootimg:
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
    command: usr/bin/python3 $SNAP/usr/bin/unpack_bootimg
    plugs: [ home, removable-media ]
  repack-bootimg:
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
    command: usr/bin/python3 $SNAP/usr/bin/repack_bootimg
    plugs: [ home, removable-media ]
  avbtool:
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
    command: usr/bin/python3 $SNAP/usr/bin/avbtool
    plugs: [ home, removable-media ]

parts:
  tools:
    plugin: cmake
    source: .
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DANDROID_TOOLS_USE_BUNDLED_FMT=ON
      - -DANDROID_TOOLS_USE_BUNDLED_LIBUSB=ON
      - -DANDROID_TOOLS_LIBUSB_ENABLE_UDEV=ON
    build-environment:
      - PATH: /opt/android-tools-build/bin:$PATH
    override-build: |
      # Prepare sources
      cd $CRAFT_PART_SRC
      git config --global --add safe.directory .
      git submodule update --init
      git submodule foreach 'git config --global --add safe.directory $path'
      find .git/ -type f -name rebase-apply -delete

      # Package version
      craftctl set version="37.0.0"

      # Workaround protoc being called without required argument
      mkdir -p /opt/android-tools-build/bin
      echo -e "#!/bin/bash\n/usr/bin/protoc \$@ --experimental_allow_proto3_optional" > /opt/android-tools-build/bin/protoc
      chmod 755 /opt/android-tools-build/bin/protoc

      craftctl default
    override-stage: |
      craftctl default
      cd $CRAFT_STAGE
      rm usr/bin/mkbootimg
      ln -sf ../share/android-tools/mkbootimg/mkbootimg.py usr/bin/mkbootimg
    build-packages:
      - git
      - cmake
      - build-essential
      - dpkg-dev
      - libpcre2-dev
      - googletest
      - libprotobuf-dev
      - libbrotli-dev
      - libzstd-dev
      - liblz4-dev
      - libudev-dev
      - perl
      - pkg-config
      - protobuf-compiler
      - libgtest-dev
    stage-packages:
      - openssl
      - python3-minimal
      - python3.12-minimal
      - libbrotli1
      - libzstd1
      - liblz4-1
      - libprotobuf32t64
